Clients should locally save metadata
heartsucker/rust-tuf pull request #157
Opened 2018-08-09 05:38 UTC by erickt

This patch merges `Client::update_local` and `Client::update_remote` in order to update `Tuf` following the pattern as described in the [spec section 5.1](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#the-client-application).

One potential problem though is I'm not sure how we can atomically update the local repository and the `Tuf` object, so for ease of implementation, this patch will update `Tuf` and could potentially error out writing the metadata to the local repository. We could instead implement some sort of rollback mechanism to `Tuf`, but I figure we can do that later if it's necessary.

Closes #153.

2018-08-25 07:24 UTC, heartsucker requested changes
One small change.

2018-08-25 07:24 UTC, heartsucker commented on src/client.rs
> +                .store_metadata(&root_path, &root_version, &signed_root)?;
I think we don't need to roll back the version number. The in-memory `Tuf` struct in memory is the absolute truth. The local repo is just for convenience and caching. We could issue a warning.

2018-08-25 07:24 UTC, heartsucker commented on src/client.rs
> +        self.local.store_metadata(
See above comment.

2018-08-25 07:24 UTC, heartsucker commented on src/client.rs
> +        // FIXME should we also the root as `MetadataVersion::None`?
I think we need to store the latest as unversioned too since that would allow us in some cases to short cut and skip all the lower versions. If we don't the client might try to fetch it remotely thinking there is no local root at all. This isn't the current behavior, but this is a hedge against regressions.

2018-08-25 07:24 UTC, heartsucker commented on src/client.rs
> +            self.local.store_metadata(
See above. No rollback.

2018-08-25 07:24 UTC, heartsucker commented on src/client.rs
> +            // FIXME what if this fails? do we need to roll back `self.tuf`s version?
This is non-trivial. We'd have to actually keep all the TUF metadata in memory for all versions and then try to roll back to a consistent state of

1) Valid root chain
2) Valid time stamp pointing to:
3) A valid snapshot pointing to:
4) A valid targets (optionally pointing to valid delegations)

This is a huge ask. I think the simplest thing to do is abort and let the application that is implementing it try to start over.

2018-08-25 07:24 UTC, heartsucker commented on src/client.rs
> +            // FIXME what if this fails? do we need to roll back `self.tuf`s version?
See above. Just keep going and log.

2018-08-29 03:16 UTC, erickt commented
@heartsucker Updated the patch to make any errors saving metadata to the local repository just a warning. Hopefully that's what you wanted.

Also, I came up with another question. When we initially create a client and if we don't have metadata locally, should we download the first metadata, or the latest one? I think the latest one since who knows how old the first metadata is, but I wanted to be safe.

Or should we make this configurable? I imagine we would need to associate pinned keys with the root metadata they came from, because if we have years of metadata, we might want to update our pinned keys to something more recent than version 1's keys, since they could have been compromised.

2018-08-29 15:30 UTC, trishankatdatadog commented
@erickt I think it's always a good idea to ship clients with at least the latest root metadata file at the time of shipping. But if the client for some reason doesn't have anything, then it's best to download the latest root metadata file over TLS, but this implies TOFU: if the server has been compromised, then the client is in trouble.

2018-08-29 15:31 UTC, trishankatdatadog commented
Sorry, I hope you guys don't mind I jumped into the conversation :)

2018-09-04 16:22 UTC, erickt commented
@trishankatdatadog please do jump into these conversations! That's very helpful. I suppose if we really don't have some pinned keys to start from, it doesn't really matter what version we start from. I opened #162 to track this.

@heartsucker friendly ping :)

2018-09-11 08:56 UTC, heartsucker approved these changes

2018-09-11 08:56 UTC, merged