Drop MetadataVersion::Hash, resolve #254
heartsucker/rust-tuf pull request #262
Opened 2020-01-02 17:24 UTC by cavokz

2020-01-02 22:18 UTC, erickt requested changes
Thanks for this! Other than my in-line comment, can you also:

* check if python-tuf is fetching delegations by version number, just to be safe?
* add a test to make sure we are fetching delegations by version number. Simplest would be to extend src/client.rs's `test_versioned_init` with a delegation. You can find how to make a delegation by looking at tests/integration.rs.

2020-01-02 22:18 UTC, erickt commented on src/client.rs
> -                MetadataVersion::Hash(value.clone())
I think we want this conditional, just returning `MetadataVersion::Number(role_meta.version())` when consistent snapshot is enabled.

2020-01-03 09:30 UTC, cavokz commented
I addressed the inline comment, I'll handle the test extension in a separate commit. I still need to understand a few more things. Thanks!

2020-10-23 23:30 UTC, erickt approved these changes

2020-11-05 00:14 UTC, erickt commented
This was incorporated into another PR that has since landed. Thanks!

2020-11-05 00:14 UTC, closed without merging