Add a new repository builder
heartsucker/rust-tuf pull request #336
Opened 2021-12-17 23:03 UTC by erickt

This introduces a new repository builder. It greatly simplifies creating metadata for a repository. Here's a simple example that creates a repository, with an empty targets metadata, and commiting it to a repository.

```rust
let key = Ed25519PrivateKey::from_pkcs8("...").unwrap();
let repo = EphemeralRepository::new();
let _metadata = RepoBuilder::<Json>::create()
    .trusted_root_key(&key)
    .trusted_targets_key(&key)
    .trusted_snapshot_key(&key)
    .trusted_timestamp_key(&key)
    .commit(&repo)
    .await
    .unwrap();
```

It also supports generating new metadata derived off of a TUF database:

```
let client: tuf::Client = ...;
client.update().await().unwrap();

let _metadata2 = RepoBuilder::from_database(client.database())
    .trusted_root_key(&key)
    .trusted_targets_key(&key)
    .trusted_snapshot_key(&key)
    .trusted_timestamp_key(&key)
    .create_root()
    .unwrap()
    .commit(&repo)
    .await
    .unwrap();
```

Unfortunately RepoBuilder does not yet take care of publishing targets to a repository, or generating target delegations. Those will come in a future path.

Note, this is built upon #331, #332, #333, #334, and #335, so those should be reviewed first to avoid excess churn.

2022-01-26 19:05 UTC, wittrock requested changes
This looks quite good. Much simpler for clients. If you want to discuss the cost/benefits of requiring users to step through the typestate, happy to meet, but I like how clean it is now. 

Just a few questions and nits.

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +    pub trait Sealed {}
A little strange to have a pub trait in a mod called `private`. Is this a common Rust idiom?

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +    pub trait Sealed {}
Also, rustdoc pls :)

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +impl State for Root {}
I think this should go nearer the definition of State

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +                signing_root_keys: vec![],
I am probably missing something, but shouldn't we initialize most of the context here? Seems weird to leave it blank.

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +    /// Create a targets metadata using the default settings.
Would be good to get more specific on what 'create' means here. It seems like it just directs the builder to do this _later_, rather than doing it now.

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +    /// * If the [RepoBuilder] was created for a new repository,  was created with a [Database], the version will be 1
nit: line length is inconsistent.

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +    /// Generate a new metadata This function will generate a new root metadata,
nit: missing period

2022-01-26 19:05 UTC, wittrock commented on tuf/src/repo_builder.rs
> +    /// * The metadata has expired.
It seems like these are conditions that would require a new targets, but that's not clear from this doc comment.

2022-01-27 01:05 UTC, erickt commented on tuf/src/repo_builder.rs
> +    pub trait Sealed {}
I'll add some comments.

Yeah, this is implementing the [sealed trait pattern](https://rust-lang.github.io/api-guidelines/future-proofing.html). It's a way to declare a public trait, but make sure people outside the repository can't implement it.

2022-01-27 01:07 UTC, erickt commented on tuf/src/repo_builder.rs
> +impl State for Root {}
done

2022-01-27 20:01 UTC, erickt commented on tuf/src/repo_builder.rs
> +                signing_root_keys: vec![],
This was one of the areas I was playing around with. What I'm trying to allow is that users should be able to generate metadata if they only have a subset of keys. One common workflow is that you want to automatically generate new timestamps to keep them from expiring. To do this, you typically want to leave the timestamp keys online. But generally you want to keep the root keys offline. This means that all these keys are ultimately optional.

So the two ways I approached this was here, and to also define a notion of a `KeySet`, which would then hold all these key values, and a `KeySetBuilder`, that allows you to make these functions. But I decided to squash the two together since I couldn't think of a logical reason why we'd want to work with the keyset as an independent thing. It'd just be something we'd make, then immediately pass to the builder.

I could go either way. Do you think the ux would be more obvious if you had to first gather up all the keys before trying to build a repo?

2022-01-27 20:01 UTC, erickt commented on tuf/src/repo_builder.rs
> +                signing_root_keys: vec![],
Also, I forgot to add a test to verify that the keys aren't required to be online. I added one.

2022-01-27 20:01 UTC, erickt commented on tuf/src/repo_builder.rs
> +    /// * If the [RepoBuilder] was created for a new repository,  was created with a [Database], the version will be 1
fixed

2022-01-27 20:01 UTC, erickt commented on tuf/src/repo_builder.rs
> +    /// Generate a new metadata This function will generate a new root metadata,
fixed

2022-01-27 20:01 UTC, erickt commented on tuf/src/repo_builder.rs
> +    /// Create a targets metadata using the default settings.
Would `stage_targets()` read better here and elsewhere? And maybe `stage_targets_if_necessary()`?

2022-01-28 00:46 UTC, erickt reviewed
I've pushed up a new version that tries to address all the comments. One of the major things I did was that I've gotten rid of most of the overloaded functions. It really cluttered up the rustdoc, and I think it'd be rather rare to actually use the overloads. We could always add them back if necessary.

2022-01-28 00:46 UTC, erickt commented on tuf/src/repo_builder.rs
> +    /// Create a targets metadata using the default settings.
I renamed things from `create_*` and `with_*_builder` to to `stage_*` and `stage_*_with_builder`. I think that reads a bit better.

2022-01-28 00:46 UTC, erickt commented on tuf/src/repo_builder.rs
> +    /// * The metadata has expired.
I've rephrased it in the latest version. Does it read better?

2022-01-28 16:56 UTC, wittrock approved these changes
LGTM

2022-01-28 16:56 UTC, wittrock commented on tuf/src/repo_builder.rs
> +    pub trait Sealed {}
Thanks!

2022-01-28 17:19 UTC, merged