Improve errors
heartsucker/rust-tuf pull request #363
Opened 2022-07-14 00:19 UTC by erickt

This PR cleans up the errors to include better information:

* missing metadata or target path is now included in relevant errors.
* unused error variants are removed.
* makes variants for common errors.

2022-07-14 03:22 UTC, wellsie1116 requested changes
errors improved, nice.  Looks like there are some CI failures to address first.

2022-07-14 03:25 UTC, erickt commented
Those pesky features. Should hopefully be fixed now.

2022-07-14 03:27 UTC, wellsie1116 reviewed
TIL clicking the wrong start review button deletes all my comments

2022-07-14 03:27 UTC, wellsie1116 commented on tuf/src/error.rs
> +    #[error("derp: {0}")]
"derp" is a cute name, but maybe we should indicate what that means in the error string. "der parse: {0}"?

2022-07-14 03:27 UTC, wellsie1116 commented on tuf/src/error.rs
>      #[error("bad signature")]
let's include the path in the error string

2022-07-14 03:38 UTC, kellerb commented on tuf/src/error.rs
> +    #[error("IO: {0}")]
we've been not including source errors in the display text and then using anyhow to stringify the errors for logging, which itself includes the source errors in the stringification

not sure if that pattern would be useful here

2022-07-14 03:38 UTC, kellerb commented on tuf/src/metadata.rs
> +            Err(Error::MetadataMissingSignatures { role, number_of_valid_signatures: 1, threshold: 2 })
some line wraps in the following assert_matches

2022-07-15 15:34 UTC, erickt commented on tuf/src/error.rs
>      #[error("bad signature")]
done

2022-07-15 15:34 UTC, erickt commented on tuf/src/metadata.rs
> +            Err(Error::MetadataMissingSignatures { role, number_of_valid_signatures: 1, threshold: 2 })
done

2022-07-15 15:34 UTC, erickt commented on tuf/src/error.rs
> +    #[error("derp: {0}")]
I switched back to the old error writing the error in the `Encoding` variant. I think I want to eventually hide derp properly, but I figure I can do that later.

2022-07-15 15:34 UTC, erickt commented on tuf/src/error.rs
> +    #[error("IO: {0}")]
seems reasonable. done.

2022-07-18 17:37 UTC, kellerb approved these changes

2022-07-18 22:08 UTC, merged